### ISSUE TITLE
Too bloated for being a simple site with a simple goal

### ISSUE THREAD

**Issue by julianxhokaxhiu** [JordanMajd/isjsenabled.com#1]
This issue should serve as a tracking point for whomever is willing to improve the website ending HTML and the way it is styled.

By cold analyzing the HTML in the final domain I noticed the following things:
-> Google Analytics ( really? I mean, which kind of business use case you can have around it? )
-> Styles as Javascript: this can be HEAVILY improved by just swapping a class on the body and style at your own pleasure
-> CSS not cachable: how often will it be changed that has to be served on the HTML page? Can't it be a separate file?

Thank you in advance and I hope you get this issue as a constructive one. I may also later come up with a PR adressing the following issues.

Best regards,
Julian

**Comment by JordanMajd** [comment]
I agree, Google Analytics is _very_ bloated, but stays for the time being as it is a project requirement. I do plan on replacing it with a lighter weight and less invasive solution. 

While changing styles in Javascript is a code smell, it isn't a big deal in a project of this size as only two elements are modified. Although, I would entertain the change.

The CSS/JS/HTML are 2.5KB total loaded and fetched / cached as a single resource. I don't see an issue with this. Separating the CSS would allow for it to be cached separately but would slow down how fast the site loads and renders by forcing the browser the download and parse the HTML before requesting the CSS, blocking the page from rendering until it had loaded. See [Render Blcoking CSS](https://developers.google.com/web/fundamentals/performance/critical-rendering-path/render-blocking-css) and [Ultrafast Loading of CSS](https://www.peterbe.com/plog/ultrafast-loading-of-css) for more information. 

If bloat is the biggest concern, the biggest returns would be GA (42KB) SVGs (4.7KB each), the Favicon is (3.2KB).

**Comment by julianxhokaxhiu** [comment]
Hi,

sorry for my late reply. I see a valid point in your reply.

I'll stay tuned for further optimizations, and I'll close this issue meanwhile.

Best regards.

**Comment by JordanMajd** [comment]
Fuck me,

I don't like google analytics but I wanted to be able to track page views until I dropped in a privacy friendly replacement.

As much as I want to know how many users I'm getting, I'd rather not have google farming users data.

Reopening to remove google analytics.

**Comment by JordanMajd** [comment]
Resolved by 4830adf
